### PR TITLE
New tutorial: ddls extend

### PR DESCRIPTION
**Pull request by Liebherr**
Hi Arianna and Achim, can someone of you two please quickly review my brand new tutorial layout wise. Content and language review has been done extensively already.  Its available under https://developers-qa-blue.wcms-nonprod.c.eu-de-2.cloud.sap/tutorials/abap-env-ddls-extend.html
Thanks and Regards
Ulrike

### CODE REVIEW

**Review by Liebherr — COMMENTED** [review]
Already found an issue in step 4 myself, please wait with your review

**Comment by AriannaMussoBarcucci** [comment]
Ok!
Let us know when we can proceed with the review 😊

Cheers,
Arianna

**Review by Liebherr — COMMENTED** [review]
Now! :)

**Comment by AriannaMussoBarcucci** [comment]
Review sent via email, once those comments are addressed, from my side you can go ahead and merge :)

**Review by Liebherr — COMMENTED** [review]
Q: Can you format the “I_SalesOrder” and “vbak” words in the description to match how they are formatted in the text? I forgot if you can format words in the description…?
A: The description unfortunately doesn’t allow formatting

Q: Some screenshots are missing the black border (in step 2, step 7, step 8, step 10, step 11, step 12 and step 13)
A: I refrain from the border if the screenshot is showing a single window completely, so that the window border itself serves as a border  

Q: In step 8, the numbering of the substeps goes 1,2,3,4,5 and then 1,2. Is this on purpose?
A:Yes, that’s intended, as the first part is creating the data source and the second testing it from the class

Q: This happens also in step 12.
A: See above

**Pull request merged**
